packages:
  - "packages/*"
  - "site"

onlyBuiltDependencies:
  - "argon2"

overrides:
  vitest: 4.1.10
  "@better-auth/utils": "0.5.0"
  uuid: ^14.0.0
  chromium-edge-launcher: ^2.0.1
  babel-plugin-istanbul: ^8.0.2
  test-exclude: ^8.0.0

peerDependencyRules:
  allowedVersions:
    "@better-auth/utils": ">=0.4.2 <0.6.0"
