export type {
  AgentCapabilityConstraint,
  AgentCapabilityConstraintPrimitive,
  AgentCapabilityGrantSnapshot,
  AgentMode,
  AgentPrincipal,
  AnonymousPrincipal,
  ApiCredentialType,
  ApiKeyPrincipal,
  ApiResolvedAuthContext,
  AuthPrincipal,
  AuthProvider,
  ExecutionContext,
  NormalizedAuthIdentity,
  NormalizedIdentityProviderKey,
  OAuthClientPrincipal,
  ResolvedAuthContext,
  ServicePrincipal,
  UserPrincipal,
  VerifiedApiCredential,
  VerifiedApiKeyToken,
  VerifiedUserToken,
} from "../compat/convex/coreTypes";
